### ISSUE TITLE
Error calculating osds up.

### ISSUE THREAD

**Issue by fbarbeira** [ceph/ceph-ansible#6016]
**Bug Report**

What happened:

```
TASK [ceph-osd : wait for all osd to be up] *****************************************************************************************************************************************************************************************************************
Wednesday 11 November 2020  09:05:16 +0100 (0:00:01.750)       0:04:56.348 ****
skipping: [node01]
skipping: [node02]
skipping: [node03]
fatal: [node04]: FAILED! =>
  msg: 'The conditional check ''(wait_for_all_osds_up.stdout | from_json)["osdmap"]["num_osds"] | int > 0'' failed. The error was: error while evaluating conditional ((wait_for_all_osds_up.stdout | from_json)["osdmap"]["num_osds"] | int > 0): ''dict object'' has no attribute ''osdmap'''
```

What you expected to happen:

```
TASK [ceph-osd : wait for all osd to be up] *****************************************************************************************************************************************************************************************************************
Wednesday 11 November 2020  09:38:27 +0100 (0:00:01.436)       0:05:12.771 ****
skipping: [node01]
skipping: [node02]
skipping: [node03]
ok: [node04 -> monitor01]
```

How to reproduce it (minimal and precise):

Running the playbook. I was adding node04 to the cluster. All OSDs were up when I ran the playbook.

I think it's related with this commit: https://github.com/ceph/ceph-ansible/commit/b9cb0f12e9e79600f1a974dd88ba1ed1d833211f

If I remove the `["osdmap"]` parts and put the file exactly like `master` branch, everything works fine:

```
-    - (wait_for_all_osds_up.stdout | from_json)["osdmap"]["num_osds"] | int > 0
-    - (wait_for_all_osds_up.stdout | from_json)["osdmap"]["num_osds"] == (wait_for_all_osds_up.stdout | from_json)["osdmap"]["num_up_osds"]
+    - (wait_for_all_osds_up.stdout | from_json)["num_osds"] | int > 0
+    - (wait_for_all_osds_up.stdout | from_json)["num_osds"] == (wait_for_all_osds_up.stdout | from_json)["num_up_osds"]
```

**Environment**:
* OS: Ubuntu18
* Kernel: Linux node4 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Ansible version: ansible-playbook 2.9.13 - python version 3.8.5
* ceph-ansible version: stable-4.0
* Ceph version: ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)

**Comment by dsavineau** [comment]
That's unfortunate because the `osd stat` json structure seems to have changed between 14.2.7 and 14.2.8 to reflect the `ceph status` output.

```console
# ceph --version
ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)
# ceph -s -f json | jq .osdmap
{
  "osdmap": {
    "epoch": 13,
    "num_osds": 1,
    "num_up_osds": 1,
    "num_in_osds": 1,
    "num_remapped_pgs": 0
  }
}
# ceph osd stat -f json | jq .osdmap
null
```

```console
# ceph --version
ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)
# ceph -s -f json | jq .osdmap
{
  "osdmap": {
    "epoch": 13,
    "num_osds": 1,
    "num_up_osds": 1,
    "num_in_osds": 1,
    "num_remapped_pgs": 0
  }
}
# ceph osd stat -f json | jq .osdmap
{
  "epoch": 13,
  "num_osds": 1,
  "num_up_osds": 1,
  "num_in_osds": 1,
  "num_remapped_pgs": 0
}
```

So if you change this in stable-4.0 this won't work with ceph nautilus version from 14.2.8 to 14.2.13.

it's probably better for you to either:
  - stick on a commit before 8bc0806f102b00be57bef92b22833e7f8451efa7 on stable-4.0 branch
  - upgrade your cluster to newer nautilus version.

**Comment by fbarbeira** [comment]
Ok! I will stick on that commit and start planning cluster upgrade.

Thanks a lot :)

**Comment by dbenduga** [comment]
@dsavineau 
I am trying to upgrade ceph  nautilus  from 14.2.7 to latest version (14.2.16) 
Using stable 4.0 branch while upgrading ceph cluster however getting error message. 

[dbenduga@gc1-tool-1 ceph-ansible]$ git branch
  master
* stable-4.0
[dbenduga@gc1-tool-1 ceph-ansible]$

---error---
fatal: [gc1-ceph-osd-6]: FAILED! =>
  msg: 'The conditional check ''(wait_for_all_osds_up.stdout | from_json)["osdmap"]["num_osds"] | int > 0'' failed. The error was: error while evaluating conditional ((wait_for_all_osds_up.stdout | from_json)["osdmap"]["num_osds"] | int > 0): ''dict object'' has no attribute ''osdmap'''

**Comment by guits** [comment]
@dbenduga that must be because of what @dsavineau has already explained:

> it's probably better for you to either:
>
> - stick on a commit before 8bc0806 on stable-4.0 branch
> - upgrade your cluster to newer nautilus version.
