### ISSUE TITLE
Regression: stable-5.0 deployment fails after https://github.com/ceph/ceph-ansible/pull/5887

### ISSUE THREAD

**Issue by SvenMW** [ceph/ceph-ansible#7292]
**Bug Report**

What happened:

Ceph Octopus deployment in our virtual dev env fails with:

```yaml
TASK [ceph-client : create ceph pool(s)] ***************************************
Monday 01 August 2022  15:27:19 +0000 (0:00:00.049)       0:05:17.790 ********* 
fatal: [10.60.0.65 -> {{ delegated_node }}]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'None' has no attribute 'name'
  
    The error appears to be in '/builds/ceph-ansible/roles/ceph-client/tasks/create_users_keys.yml': line 54, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - name: create ceph pool(s)
          ^ here

```

What you expected to happen:

deployment to succed

How to reproduce it (minimal and precise):

I injected a debug task in [create_users_keys.yml](https://github.com/ceph/ceph-ansible/blob/1b49988e4aa311559287eb51dc4040584ad1472a/roles/ceph-client/tasks/create_users_keys.yml) where it fails:

```yaml
    - name: Svens Debug Output
      ansible.builtin.debug:
        msg: "the osd pool default size is: {{ osd_pool_default_size }}"
```

Error:

```
TASK [ceph-client : Svens Debug Output] ****************************************************************************************************************************************************************************************************
Thursday 11 August 2022  12:42:16 +0000 (0:00:00.086)       0:04:36.809 ******* 
fatal: [10.60.0.137]: FAILED! => 
  msg: '[''{{ images }}'', ''{{ images_data }}'', ''{{ volumes }}'', ''{{ volumes_data }}'',  
''{{ volumes_replicated }}'', ''{{ vms }}'', ''{{ vms_data }}'', ''{{ mcbu }}'',  
''{{ mcbu_data }}'']: {''name'': ''images'', ''pg_num'': 32, ''pgp_num'': 32,  
''size'': ''{{ osd_pool_default_size }}'', ''min_size'':  
''{{ osd_pool_default_min_size }}'', ''rule_name'': ''{{ osd_pool_crush_rule_name }}'',  
''type'': 1, ''pg_autoscale_mode'': False, ''application'': ''rbd''}:  
''osd_pool_default_size'' is undefined'
```
defining `ods_pool_default_size` and friends again in my inventory fixes this.

these where defined in the role `ceph-defaults` before https://github.com/ceph/ceph-ansible/pull/5887 got merged.

I did not just yet analyze why the backport is the culprit here.

I guess it will be much easier for something more familiar with the code to debug this, if there is even interest left, given that the octopus release just reached EOL.

But in any case, if someone stumbles on this, I figured it might be nice to share this information here.

Thanks

Sven

:edit: fwiw this is a non containerized deployment on ubuntu virtual machines.

**Comment by guits** [comment]
this is a bit confusing

```
The task includes an option with an undefined variable. The error was: 'None' has no attribute 'name'
```

what does it have to do with `osd_pool_default_size` ?

**Comment by guits** [comment]
```
The error appears to be in '/builds/ceph-ansible/roles/ceph-client/tasks/create_users_keys.yml': line 54
```

this task has even not a single reference to `osd_pool_default_size`

I would be curious to see your group_vars/host_vars and inventory host file (which should have been provided when filing that issue...)

**Comment by SvenMW** [comment]
yeah, sorry, will provide more details tomorrow

**Comment by SvenMW** [comment]
Sorry, this might take some more time, there are some higher priorities right now.

Hope I can provide more details soon (TM).

**Comment by SvenMW** [comment]
nevermind, this seems to be an error in our local playbook, sorry for the noise!
